import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DailyReport, Project, AuditLog } from '../types';
import { saveOrShareFile } from './fileExportService';

export interface ParsedReportNotes {
  activityTitle?: string;
  disciplinePackage?: string;
  overallProgress?: string;
  outputMeasured?: string;
  hoursLogged?: string;
  priorityLevel?: string;
  fieldRemarks?: string;
  subtasks: {
    no: string;
    title: string;
    category: string;
    status: string;
    quantity: string;
    isMilestone: boolean;
    isHoldPoint?: boolean;
    holdPointApproved?: boolean;
    holdPointSigner?: string;
  }[];
  crewText?: string;
  machineryText?: string;
  materialsText?: string;
  weatherText?: string;
  siteConditionText?: string;
  rawText?: string;
}

/**
 * Smart helper to parse structured supervisor notes generated by Log Progress or daily entries
 */
export function parseSupervisorNotes(notes: string): ParsedReportNotes {
  const result: ParsedReportNotes = {
    subtasks: [],
    rawText: notes
  };

  if (!notes) return result;

  const lines = notes.split('\n');
  let currentSection = '';
  const remarksBuffer: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    if (!line) continue;

    // Detect Activity Title
    if (line.startsWith('DAILY ACTIVITY PROGRESS SNAPSHOT:')) {
      result.activityTitle = line.replace('DAILY ACTIVITY PROGRESS SNAPSHOT:', '').trim();
      continue;
    }

    // Detect Project / Discipline
    if (line.startsWith('Discipline / Package:')) {
      result.disciplinePackage = line.replace('Discipline / Package:', '').trim();
      continue;
    }

    // Detect Sections
    if (line.includes('1. OVERALL PROGRESS & QUANTITIES:')) {
      currentSection = 'progress';
      continue;
    } else if (line.includes('2. FIELD REMARKS & OBSERVATIONS:') || line.includes('2. FIELD REMARKS & ACCOMPLISHMENTS')) {
      currentSection = 'remarks';
      continue;
    } else if (line.includes('3. SUBTASK & EXECUTION BREAKDOWN')) {
      currentSection = 'subtasks';
      continue;
    } else if (line.includes('4. CREW & MACHINERY ALLOCATED ON TASK:')) {
      currentSection = 'resources';
      continue;
    } else if (line.includes('5. ENVIRONMENTAL & SITE CONDITIONS:')) {
      currentSection = 'environment';
      continue;
    }

    // Section Content Extraction
    if (currentSection === 'progress') {
      if (line.includes('Current Status:') || line.includes('Completion Status:')) {
        result.overallProgress = line.split(':')[1]?.trim();
      } else if (line.includes('Output Measured:')) {
        result.outputMeasured = line.split(':')[1]?.trim();
      } else if (line.includes('Actual Hours Logged:') || line.includes('Labour Hours Logged:')) {
        result.hoursLogged = line.split(':')[1]?.trim();
      } else if (line.includes('Priority Level:')) {
        result.priorityLevel = line.split(':')[1]?.trim();
      }
    } else if (currentSection === 'remarks') {
      if (!line.startsWith('3.')) {
        remarksBuffer.push(line);
      }
    } else if (currentSection === 'subtasks') {
      // Example line: [✓] #1 Trench set-out (Excavation & Earthworks) - Completed [Qty: 433/433 m] 🎯 Milestone [🔒 QA Approved: John Doe]
      const subtaskMatch = line.match(/^\[([✓►* xX ])?\]?\s*(#\d+)?\s*(.*?)(?:\(([^)]+)\))?\s*-\s*([A-Za-z ]+)(?:\[Qty:\s*([^\]]+)\])?(.*)$/);
      if (subtaskMatch) {
        const checkMark = subtaskMatch[1] || '';
        const no = subtaskMatch[2] || `#${result.subtasks.length + 1}`;
        const title = (subtaskMatch[3] || '').trim();
        const category = (subtaskMatch[4] || 'General').trim();
        let status = (subtaskMatch[5] || '').trim();
        const qty = (subtaskMatch[6] || '-').trim();
        const rest = subtaskMatch[7] || '';
        const isMilestone = rest.includes('Milestone') || rest.includes('🎯');
        const isHoldPoint = rest.includes('QA Approved') || rest.includes('QA Hold Point') || rest.includes('🔒');
        const holdPointApproved = rest.includes('QA Approved');
        const signerMatch = rest.match(/QA Approved:\s*([^\]]+)/);
        const holdPointSigner = signerMatch ? signerMatch[1].trim() : undefined;

        if (!status) {
          status = checkMark === '✓' ? 'Completed' : checkMark === '►' ? 'In Progress' : 'Not Started';
        }

        result.subtasks.push({
          no,
          title: title || `Subtask ${no}`,
          category,
          status,
          quantity: qty,
          isMilestone,
          isHoldPoint,
          holdPointApproved,
          holdPointSigner
        });
      }
    } else if (currentSection === 'resources') {
      if (line.includes('Assigned Personnel') || line.includes('Personnel (')) {
        result.crewText = line.split(':')[1]?.trim();
      } else if (line.includes('Assigned Machinery') || line.includes('Machinery (')) {
        result.machineryText = line.split(':')[1]?.trim();
      } else if (line.includes('Allocated Materials:')) {
        result.materialsText = line.split(':')[1]?.trim();
      }
    } else if (currentSection === 'environment') {
      if (line.includes('Weather:')) {
        result.weatherText = line.split(':')[1]?.trim();
      } else if (line.includes('Site Condition:') || line.includes('Site / Ground:')) {
        result.siteConditionText = line.split(':')[1]?.trim();
      }
    }
  }

  result.fieldRemarks = remarksBuffer.join('\n').trim();
  return result;
}

/**
 * Export a single Daily Activity Report as a high-end, executive PDF document using client-side jsPDF.
 */
export function exportSingleReportPDF(report: DailyReport, projectName: string) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const parsed = parseSupervisorNotes(report.supervisorNotes || '');

  // Executive Color Palette
  const deepNavy = [15, 23, 42] as [number, number, number]; // #0F172A
  const royalBlue = [11, 95, 255] as [number, number, number]; // #0B5FFF
  const slateHeader = [30, 41, 59] as [number, number, number]; // #1E293B
  const textDark = [30, 41, 59] as [number, number, number];
  const textMuted = [100, 116, 139] as [number, number, number];
  const lightBg = [248, 250, 252] as [number, number, number]; // #F8FAFC
  const borderGray = [226, 232, 240] as [number, number, number]; // #E2E8F0
  const successGreen = [16, 185, 129] as [number, number, number]; // #10B981

  // 1. Executive Top Navy Header Banner
  doc.setFillColor(...deepNavy);
  doc.rect(0, 0, 210, 26, 'F');

  // Accent Stripe
  doc.setFillColor(...royalBlue);
  doc.rect(0, 26, 210, 1.8, 'F');

  // Title Text
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('CONSTRUCT OS  |  OFFICIAL DAILY SITE REPORT', 14, 13);

  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.setFont('helvetica', 'normal');
  doc.text('Contractor Daily Site Operations Record & QA Execution Summary', 14, 20);

  // Right Side Header Badge
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(`REPORT NO: ${report.id}`, 196, 12, { align: 'right' });

  doc.setFontSize(7.5);
  doc.setTextColor(191, 219, 254);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date Logged: ${report.date}   |   Status: VERIFIED`, 196, 19, { align: 'right' });

  // 2. Project & Scope Overview Card
  const activePackage = parsed.disciplinePackage || 'Civil, Electrical & Quality Management';
  const activeTitle = parsed.activityTitle || (report.activitiesLogged?.[0] ? report.activitiesLogged[0].split(' - ')[0] : 'General Site Operations');

  autoTable(doc, {
    startY: 33,
    head: [['Project & Site Information', 'Contract & Governance Details']],
    body: [
      [
        `Project Name: ${projectName}\nWork Package: ${activePackage}\nPrimary Scope: ${activeTitle}`,
        `Report Reference: ${report.id}\nShift Date: ${report.date}\nSupervisor: Site Supervisor / Engineer\nCompliance: ISO & HSE Site Standard`
      ]
    ],
    theme: 'plain',
    headStyles: {
      fillColor: lightBg,
      textColor: deepNavy,
      fontStyle: 'bold',
      fontSize: 8.5,
      cellPadding: { top: 3, bottom: 3, left: 4, right: 4 }
    },
    bodyStyles: {
      fontSize: 8,
      textColor: textDark,
      cellPadding: { top: 3.5, bottom: 3.5, left: 4, right: 4 },
      lineColor: borderGray,
      lineWidth: 0.2
    },
    columnStyles: {
      0: { cellWidth: 105 },
      1: { cellWidth: 77 }
    },
    margin: { left: 14, right: 14 }
  });

  let currentY = (doc as any).lastAutoTable?.finalY || 62;

  // 3. Environmental & Site Condition KPI Grid
  const weatherVal = report.weather || parsed.weatherText || 'Sunny';
  const tempVal = report.temperature || '24°C';
  const siteCondVal = report.siteConditions || parsed.siteConditionText || 'Site dry and fully accessible';
  const workersVal = report.workersOnSite || 1;
  const equipVal = report.equipmentRunning || 0;
  const incidentsVal = report.incidents || 0;
  const ncrVal = report.ncr || 0;

  autoTable(doc, {
    startY: currentY + 3,
    head: [['Weather & Ground', 'Workforce Deployed', 'Plant & Machinery', 'Safety & Quality']],
    body: [[
      `${weatherVal} (${tempVal})\n${siteCondVal}`,
      `${workersVal} Active Personnel\nShift: Full Day Working`,
      `${equipVal} Machinery Units\nOperating on Task`,
      `${incidentsVal} Incidents | ${ncrVal} NCRs\n${incidentsVal === 0 ? 'HSE Compliant [Zero Harm]' : 'Action Required'}`
    ]],
    theme: 'grid',
    headStyles: {
      fillColor: slateHeader,
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
      cellPadding: 2.5
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: textDark,
      halign: 'center',
      cellPadding: 3,
      fontStyle: 'bold'
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable?.finalY || currentY + 25;

  // 4. Construction Activity Summary Table
  const activityRows = (report.activitiesLogged && report.activitiesLogged.length > 0)
    ? report.activitiesLogged.map((act, idx) => {
        const parts = act.split(' - ');
        const nameAndId = parts[0] || act;
        const prog = parts[1] || parsed.overallProgress || '100%';
        const qty = parts[2] || parsed.outputMeasured || 'Logged';
        return [
          `#${idx + 1}`,
          nameAndId,
          activePackage,
          qty,
          prog,
          'IN PROGRESS'
        ];
      })
    : [[
        '#1',
        activeTitle,
        activePackage,
        parsed.outputMeasured || 'Logged',
        parsed.overallProgress || 'Logged',
        'IN PROGRESS'
      ]];

  doc.setFontSize(9.5);
  doc.setTextColor(...deepNavy);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Active Construction Tasks & Output Summary', 14, currentY + 6);

  autoTable(doc, {
    startY: currentY + 8,
    head: [['No.', 'Activity / Work Item', 'Discipline & Scope', 'Output Measured', 'Progress', 'Status']],
    body: activityRows,
    theme: 'grid',
    headStyles: {
      fillColor: royalBlue,
      textColor: 255,
      fontSize: 8,
      fontStyle: 'bold',
      cellPadding: 2.5
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: textDark,
      cellPadding: 2.5
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 55, fontStyle: 'bold' },
      2: { cellWidth: 50 },
      3: { cellWidth: 25, halign: 'center' },
      4: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
      5: { cellWidth: 22, halign: 'center', textColor: successGreen, fontStyle: 'bold' }
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable?.finalY || currentY + 25;

  // 5. Subtask & Method Statement Execution Breakdown (Rendered as Crisp Structured Table)
  if (parsed.subtasks && parsed.subtasks.length > 0) {
    const completedCount = parsed.subtasks.filter(s => s.status.toLowerCase().includes('completed')).length;
    const totalCount = parsed.subtasks.length;
    const subtaskPct = Math.round((completedCount / totalCount) * 100);

    doc.setFontSize(9.5);
    doc.setTextColor(...deepNavy);
    doc.setFont('helvetica', 'bold');
    doc.text(`2. Subtask & Method Statement Breakdown (${completedCount}/${totalCount} Completed • ${subtaskPct}%)`, 14, currentY + 7);

    const subtaskBody = parsed.subtasks.map((s, idx) => {
      const isDone = s.status.toLowerCase().includes('completed');
      const isProg = s.status.toLowerCase().includes('progress');
      const statusLabel = isDone ? 'COMPLETED [✓]' : isProg ? 'IN PROGRESS [►]' : 'NOT STARTED [ ]';
      return [
        s.no || `#${idx + 1}`,
        s.title,
        s.category,
        s.quantity || '-',
        s.isMilestone ? '🎯 MILESTONE' : 'Standard',
        statusLabel
      ];
    });

    autoTable(doc, {
      startY: currentY + 9,
      head: [['No.', 'Subtask / Work Deliverable', 'Category / Trade', 'Quantity Measured', 'Milestone', 'Execution Status']],
      body: subtaskBody,
      theme: 'striped',
      headStyles: {
        fillColor: slateHeader,
        textColor: 255,
        fontSize: 7.5,
        fontStyle: 'bold',
        cellPadding: 2.5
      },
      bodyStyles: {
        fontSize: 7,
        textColor: textDark,
        cellPadding: 2
      },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 60, fontStyle: 'bold' },
        2: { cellWidth: 40 },
        3: { cellWidth: 26, halign: 'center' },
        4: { cellWidth: 20, halign: 'center' },
        5: { cellWidth: 26, halign: 'center', fontStyle: 'bold' }
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 5) {
          const val = String(data.cell.raw || '');
          if (val.includes('COMPLETED')) {
            data.cell.styles.textColor = [16, 185, 129]; // Emerald
          } else if (val.includes('IN PROGRESS')) {
            data.cell.styles.textColor = [11, 95, 255]; // Blue
          } else {
            data.cell.styles.textColor = [100, 116, 139]; // Slate
          }
        }
        if (data.section === 'body' && data.column.index === 4) {
          const val = String(data.cell.raw || '');
          if (val.includes('MILESTONE')) {
            data.cell.styles.textColor = [217, 119, 6]; // Amber
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable?.finalY || currentY + 30;
  }

  // 6. Site Resource Allocations (Labour, Machinery & Materials)
  const hasLabour = (report.manpowerBreakdown && report.manpowerBreakdown.length > 0) || parsed.crewText;
  const hasEquipment = (report.equipmentLogged && report.equipmentLogged.length > 0) || parsed.machineryText;
  const hasMaterials = parsed.materialsText;

  if (hasLabour || hasEquipment || hasMaterials) {
    if (currentY > 230) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...deepNavy);
    doc.setFont('helvetica', 'bold');
    doc.text('3. Site Resource Allocations & Active Personnel', 14, currentY + 6);

    const resourceRows: string[][] = [];
    if (report.manpowerBreakdown && report.manpowerBreakdown.length > 0) {
      report.manpowerBreakdown.forEach(m => {
        resourceRows.push(['Labour Workforce', m.trade, `${m.count} Worker(s)`, `${m.hours} hrs shift`]);
      });
    } else if (parsed.crewText) {
      resourceRows.push(['Labour Workforce', 'Site Deployment', `${workersVal} Worker(s)`, parsed.crewText]);
    }

    if (report.equipmentLogged && report.equipmentLogged.length > 0) {
      report.equipmentLogged.forEach(eq => {
        resourceRows.push(['Machinery & Plant', eq.equipmentId, '1 Unit', `${eq.hours} hrs (${eq.status})`]);
      });
    } else if (parsed.machineryText) {
      resourceRows.push(['Machinery & Plant', 'Active Machinery', `${equipVal} Unit(s)`, parsed.machineryText]);
    }

    if (parsed.materialsText) {
      resourceRows.push(['Allocated Materials', 'Site Consumables', '-', parsed.materialsText]);
    }

    autoTable(doc, {
      startY: currentY + 8,
      head: [['Resource Category', 'Role / Specification', 'Quantity', 'Allocation / Operational Details']],
      body: resourceRows,
      theme: 'grid',
      headStyles: {
        fillColor: slateHeader,
        textColor: 255,
        fontSize: 7.5,
        fontStyle: 'bold',
        cellPadding: 2.5
      },
      bodyStyles: {
        fontSize: 7,
        textColor: textDark,
        cellPadding: 2.5
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: 'bold' },
        1: { cellWidth: 40 },
        2: { cellWidth: 25, halign: 'center' },
        3: { cellWidth: 82 }
      },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable?.finalY || currentY + 25;
  }

  // 7. Supervisor Field Observations & Directives Box (Clean Framed Box)
  const remarksText = parsed.fieldRemarks || report.significantEvents || report.supervisorNotes || 'Daily site progress verified and executed according to project specifications.';

  if (currentY > 225) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(9.5);
  doc.setTextColor(...deepNavy);
  doc.setFont('helvetica', 'bold');
  doc.text('4. Supervisor Field Observations & Directives', 14, currentY + 6);

  autoTable(doc, {
    startY: currentY + 8,
    head: [['Site Supervisor Remarks & Observations']],
    body: [[remarksText]],
    theme: 'plain',
    headStyles: {
      fillColor: lightBg,
      textColor: deepNavy,
      fontSize: 8,
      fontStyle: 'bold',
      cellPadding: 3
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: textDark,
      cellPadding: 4,
      lineColor: royalBlue,
      lineWidth: 0.5
    },
    margin: { left: 14, right: 14 }
  });

  currentY = (doc as any).lastAutoTable?.finalY || currentY + 25;

  // 8. Attached Timestamped Site Photos
  if (report.photos && report.photos.length > 0) {
    if (currentY > 210) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...deepNavy);
    doc.setFont('helvetica', 'bold');
    doc.text(`5. Attached Site Photos & Inspection Evidence (${report.photos.length})`, 14, currentY + 6);

    currentY += 10;
    let photoX = 14;
    const photoW = 55;
    const photoH = 38;

    report.photos.forEach((photoUrl) => {
      if (photoX + photoW > 195) {
        photoX = 14;
        currentY += photoH + 8;
        if (currentY > 230) {
          doc.addPage();
          currentY = 20;
        }
      }
      try {
        doc.setDrawColor(...borderGray);
        doc.setFillColor(255, 255, 255);
        doc.rect(photoX, currentY, photoW, photoH, 'FD');
        doc.addImage(photoUrl, 'JPEG', photoX + 1, currentY + 1, photoW - 2, photoH - 2);
      } catch (err) {
        console.error('Failed to embed photo into PDF:', err);
      }
      photoX += photoW + 8;
    });

    currentY += photoH + 6;
  }

  // 9. Formal Quality Assurance Verification & Sign-Off Block
  if (currentY > 235) {
    doc.addPage();
    currentY = 20;
  }

  autoTable(doc, {
    startY: currentY + 6,
    head: [['Prepared & Verified By (Contractor Site Engineer)', 'Approved & Acknowledged By (Resident Engineer / Consultant)']],
    body: [
      [
        'Name: ____________________________________\n\nSignature: _______________________________\n\nDate: _________________   Time: ___________',
        'Name: ____________________________________\n\nSignature: _______________________________\n\nDate: _________________   Time: ___________'
      ]
    ],
    theme: 'plain',
    headStyles: {
      fillColor: slateHeader,
      textColor: 255,
      fontSize: 7.5,
      fontStyle: 'bold',
      cellPadding: 2.5
    },
    bodyStyles: {
      fontSize: 7,
      textColor: textDark,
      cellPadding: 3.5,
      lineColor: borderGray,
      lineWidth: 0.2
    },
    columnStyles: {
      0: { cellWidth: 91 },
      1: { cellWidth: 91 }
    },
    margin: { left: 14, right: 14 }
  });

  // 10. Running Running Header & Footer on all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Page 2+ Top Mini Header
    if (i > 1) {
      doc.setFontSize(7.5);
      doc.setTextColor(...textMuted);
      doc.setFont('helvetica', 'normal');
      doc.text(`Constructfield • Site Daily Report (${report.id})  |  ${projectName}`, 14, 10);
      doc.setDrawColor(...borderGray);
      doc.line(14, 12, 196, 12);
    }

    // Bottom Running Footer
    doc.setDrawColor(...borderGray);
    doc.line(14, 284, 196, 284);

    doc.setFontSize(7.5);
    doc.setTextColor(...textMuted);
    doc.setFont('helvetica', 'normal');
    doc.text('Constructfield Enterprise Construction Operations  •  Official Site Record  •  Confidential', 14, 289);
    doc.text(`Page ${i} of ${totalPages}   |   Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, 196, 289, { align: 'right' });
  }

  const filename = `Daily_Report_${report.id}_${report.date}.pdf`;
  const blob = doc.output('blob');
  saveOrShareFile({
    filename,
    blob,
    title: `Daily Report ${report.id}`,
    text: `Constructfield Daily Site Report: ${report.id}`
  });
}

/**
 * Export multiple Daily Activity Reports as a single combined PDF document.
 */
export function exportMultipleReportsPDF(reports: DailyReport[], projects: Project[], filterProjectName?: string) {
  if (reports.length === 0) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const deepNavy = [15, 23, 42] as [number, number, number];
  const royalBlue = [11, 95, 255] as [number, number, number];
  const slateHeader = [30, 41, 59] as [number, number, number];
  const textDark = [30, 41, 59] as [number, number, number];
  const textMuted = [100, 116, 139] as [number, number, number];
  const borderGray = [226, 232, 240] as [number, number, number];

  // Title Banner
  doc.setFillColor(...deepNavy);
  doc.rect(0, 0, 210, 26, 'F');

  doc.setFillColor(...royalBlue);
  doc.rect(0, 26, 210, 1.8, 'F');

  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('CONSTRUCT OS  |  CONSOLIDATED DAILY REPORTS', 14, 13);

  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.setFont('helvetica', 'normal');
  doc.text(`Scope: ${filterProjectName || 'All Projects'}   |   Total Reports: ${reports.length}`, 14, 20);

  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(`Exported: ${new Date().toISOString().split('T')[0]}`, 196, 16, { align: 'right' });

  // Reports Summary Table
  const getProjName = (id: string) => projects.find(p => p.id === id)?.name || id;

  const summaryBody = reports.map((r, i) => [
    `#${i + 1}`,
    r.id,
    r.date,
    getProjName(r.projectId),
    `${r.weather || 'Sunny'} (${r.temperature || 'N/A'})`,
    `${r.workersOnSite || 0} Workers`,
    `${r.equipmentRunning || 0} Units`,
    `${r.incidents || 0}`,
    `${r.ncr || 0}`
  ]);

  autoTable(doc, {
    startY: 33,
    head: [['No.', 'Report ID', 'Date', 'Project', 'Weather', 'Workers', 'Equipment', 'Incidents', 'NCRs']],
    body: summaryBody,
    theme: 'striped',
    headStyles: { fillColor: slateHeader, textColor: 255, fontSize: 7.5, fontStyle: 'bold', cellPadding: 2 },
    bodyStyles: { fontSize: 7, textColor: textDark, cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 10, halign: 'center' } },
    margin: { left: 14, right: 14 }
  });

  let currentY = (doc as any).lastAutoTable?.finalY || 70;

  // Individual Report Details
  reports.forEach((r, idx) => {
    if (currentY > 230) {
      doc.addPage();
      currentY = 20;
    } else {
      currentY += 8;
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...deepNavy);
    doc.setFont('helvetica', 'bold');
    doc.text(`Report #${idx + 1}: ${r.id} (${r.date}) - ${getProjName(r.projectId)}`, 14, currentY);

    const reportDetailBody = [
      ['Weather & Environment', `${r.weather || 'Clear'}, ${r.temperature || 'N/A'} (Ground: ${r.siteConditions || 'Normal'})`],
      ['Workforce & Plant Deployed', `${r.workersOnSite || 0} Personnel | ${r.equipmentRunning || 0} Machinery Units`],
      ['Safety & HSE Compliance', `${r.incidents || 0} Incidents Logged | ${r.ncr || 0} Non-Conformance Reports`],
      ['Active Tasks Logged', (r.activitiesLogged || []).join('; ') || 'General Site Progress Logged'],
      ['Supervisor Remarks', r.significantEvents || (r.supervisorNotes ? r.supervisorNotes.slice(0, 180) + '...' : 'Site operations recorded.')]
    ];

    autoTable(doc, {
      startY: currentY + 3,
      head: [['Category', 'Logged Site Information']],
      body: reportDetailBody,
      theme: 'grid',
      headStyles: { fillColor: royalBlue, textColor: 255, fontSize: 7.5, fontStyle: 'bold', cellPadding: 2 },
      bodyStyles: { fontSize: 7, textColor: textDark, cellPadding: 2 },
      columnStyles: { 0: { cellWidth: 42, fontStyle: 'bold' } },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable?.finalY || currentY + 30;
  });

  // Footer on Page(s)
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...borderGray);
    doc.line(14, 284, 196, 284);

    doc.setFontSize(7.5);
    doc.setTextColor(...textMuted);
    doc.setFont('helvetica', 'normal');
    doc.text('Constructfield Enterprise Operations  •  Official Export Record  •  Confidential', 14, 289);
    doc.text(`Page ${i} of ${totalPages}   |   Exported: ${new Date().toLocaleDateString()}`, 196, 289, { align: 'right' });
  }

  const filename = `Daily_Activity_Reports_Export_${new Date().toISOString().split('T')[0]}.pdf`;
  const blob = doc.output('blob');
  saveOrShareFile({
    filename,
    blob,
    title: 'Daily Activity Reports Export',
    text: `Constructfield Daily Activity Reports Export`
  });
}

export interface ConsolidatedActivityLogsPdfOptions {
  logs: AuditLog[];
  projects?: Project[];
  reportDate?: string;
  reportTitle?: string;
  projectName?: string;
  preparedBy?: string;
  supervisorNotes?: string;
  includeDiffs?: boolean;
  includeSignoff?: boolean;
}

/**
 * Generates and downloads a consolidated PDF summary report for selected activity/audit logs
 * for the current day or custom date range.
 */
export function exportConsolidatedActivityLogsPDF({
  logs,
  projects = [],
  reportDate = new Date().toISOString().split('T')[0],
  reportTitle = 'Consolidated Daily Activity Logs Summary',
  projectName = 'All Active Projects',
  preparedBy = 'Site Supervisor / Operations Manager',
  supervisorNotes = '',
  includeDiffs = true,
  includeSignoff = true,
}: ConsolidatedActivityLogsPdfOptions) {
  if (!logs || logs.length === 0) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Color Palette Constants
  const primaryBlue = [11, 95, 255] as [number, number, number];
  const darkNavy = [15, 23, 42] as [number, number, number];
  const slateMuted = [100, 116, 139] as [number, number, number];

  // Header Banner
  doc.setFillColor(...primaryBlue);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('CONSTRUCTFIELD  |  CONSOLIDATED ACTIVITY LOGS', 14, 13);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Official Site Daily Log  •  Target Date: ${reportDate}`, 14, 21);
  doc.text(`Report Ref: CAL-${reportDate.replace(/-/g, '')}-${logs.length}`, 140, 13);
  doc.text(`Generated: ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, 140, 21);

  // Metadata Overview
  doc.setFontSize(12);
  doc.setTextColor(...darkNavy);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle, 14, 38);

  doc.setFontSize(8.5);
  doc.setTextColor(...slateMuted);
  doc.setFont('helvetica', 'normal');
  doc.text(`Project Scope: ${projectName}`, 14, 44);
  doc.text(`Prepared By: ${preparedBy}`, 14, 49);
  doc.text(`Total Records Selected: ${logs.length} Activity Log Items`, 135, 44);
  doc.text(`Status: Verified & Immutable`, 135, 49);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 52, 196, 52);

  // Metrics Calculation
  const creates = logs.filter(l => l.actionType === 'create' || l.action.toLowerCase().includes('create') || l.action.toLowerCase().includes('add')).length;
  const updates = logs.filter(l => l.actionType === 'update' || l.action.toLowerCase().includes('update') || l.action.toLowerCase().includes('edit')).length;
  const deletes = logs.filter(l => l.actionType === 'delete' || l.action.toLowerCase().includes('delete') || l.action.toLowerCase().includes('remove')).length;
  const statusChanges = logs.filter(l => l.actionType === 'status_change' || l.action.toLowerCase().includes('status')).length;
  const uniqueUsers = new Set(logs.map(l => l.userId)).size;

  // Executive KPI summary table
  autoTable(doc, {
    startY: 56,
    head: [['Total Logs', 'Records Created', 'Edits & Updates', 'Critical Deletions', 'Status Updates', 'Active Users']],
    body: [[
      `${logs.length}`,
      `${creates}`,
      `${updates}`,
      `${deletes}`,
      `${statusChanges}`,
      `${uniqueUsers}`
    ]],
    theme: 'grid',
    headStyles: { 
      fillColor: [30, 41, 59], 
      textColor: 255, 
      fontSize: 8, 
      fontStyle: 'bold',
      halign: 'center'
    },
    bodyStyles: { 
      fontSize: 9, 
      textColor: darkNavy, 
      fontStyle: 'bold',
      halign: 'center'
    }
  });

  let currentY = (doc as any).lastAutoTable?.finalY || 75;

  // Sort logs chronologically
  const sortedLogs = [...logs].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  // Consolidated Activity Logs Table
  doc.setFontSize(10.5);
  doc.setTextColor(...darkNavy);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Daily Activity Log Breakdown', 14, currentY + 9);

  const tableRows = sortedLogs.map((log, idx) => {
    const timeStr = new Date(log.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const entityStr = `${log.entityType || 'General'}${log.entityId ? ` #${log.entityId}` : ''}`;
    
    let detailsText = log.details || '';
    if (includeDiffs && (log.previousValue || log.newValue)) {
      if (log.previousValue && log.newValue) {
        detailsText += `\n[Diff] Prev: "${log.previousValue}" ➔ New: "${log.newValue}"`;
      } else if (log.previousValue) {
        detailsText += `\n[Prev]: "${log.previousValue}"`;
      } else if (log.newValue) {
        detailsText += `\n[New]: "${log.newValue}"`;
      }
    }

    return [
      `#${idx + 1}`,
      timeStr,
      log.userId || 'System',
      entityStr,
      log.action || 'Logged Event',
      detailsText
    ];
  });

  autoTable(doc, {
    startY: currentY + 13,
    head: [['No.', 'Time', 'User / Operator', 'Entity Module', 'Action', 'Log Details & Modifications']],
    body: tableRows,
    theme: 'striped',
    headStyles: { 
      fillColor: primaryBlue, 
      textColor: 255, 
      fontSize: 8, 
      fontStyle: 'bold'
    },
    bodyStyles: { 
      fontSize: 7.5, 
      textColor: darkNavy,
      cellPadding: 2.5
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 16, halign: 'center' },
      2: { cellWidth: 30, fontStyle: 'bold' },
      3: { cellWidth: 28 },
      4: { cellWidth: 32, fontStyle: 'bold' },
      5: { cellWidth: 'auto' }
    }
  });

  currentY = (doc as any).lastAutoTable?.finalY || currentY + 50;

  // Supervisor Notes / Field Observations
  if (supervisorNotes && supervisorNotes.trim().length > 0) {
    if (currentY > 230) {
      doc.addPage();
      currentY = 20;
    } else {
      currentY += 8;
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...darkNavy);
    doc.setFont('helvetica', 'bold');
    doc.text('Supervisor Field Observations & Daily Log Notes', 14, currentY);

    doc.setFontSize(8);
    doc.setTextColor(...slateMuted);
    doc.setFont('helvetica', 'normal');
    const splitNotes = doc.splitTextToSize(supervisorNotes, 180);
    doc.text(splitNotes, 14, currentY + 5);

    currentY += splitNotes.length * 4.5 + 8;
  }

  // Sign-off & Verification Section
  if (includeSignoff) {
    if (currentY > 235) {
      doc.addPage();
      currentY = 20;
    } else {
      currentY += 8;
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...darkNavy);
    doc.setFont('helvetica', 'bold');
    doc.text('Site Management Review & Compliance Verification', 14, currentY);

    // Verification Box
    doc.setDrawColor(203, 213, 225);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, currentY + 4, 182, 28, 2, 2, 'FD');

    doc.setFontSize(7.5);
    doc.setTextColor(...slateMuted);
    doc.text('I hereby certify that the consolidated activity logs represented in this report reflect the accurate on-site events,', 18, currentY + 10);
    doc.text('labour allocations, status transitions, and audit records recorded for this operating shift.', 18, currentY + 14);

    doc.setTextColor(...darkNavy);
    doc.setFont('helvetica', 'bold');
    doc.text(`Authorized Signature: ___________________________`, 18, currentY + 24);
    doc.text(`Date Verified: ${reportDate}`, 125, currentY + 24);
  }

  // Footer on all Pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(150);
    doc.text(`Constructfield  |  Consolidated Daily Activity Logs Report  •  Page ${i} of ${totalPages}`, 14, 288);
    doc.text(`Confidential • Project Audit Trail`, 145, 288);
  }

  // Save the PDF file (Mobile APK & Desktop compatible)
  const filename = `Consolidated_Activity_Logs_${reportDate}_${logs.length}logs.pdf`;
  const blob = doc.output('blob');
  saveOrShareFile({
    filename,
    blob,
    title: 'Consolidated Activity Logs',
    text: `Constructfield Consolidated Activity Logs Report - ${reportDate}`
  });
}
