import React, { useState, useMemo, useRef } from 'react';
import { Card, CardContent } from './ui';
import { 
  X, 
  Printer, 
  FileText, 
  Calendar, 
  Clock, 
  User, 
  Building,
  CheckCircle2,
  Download
} from 'lucide-react';
import { useAppContext } from '../context/AppContext';
import { LabourLog } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface DailyLaborSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultDate?: string;
}

export function DailyLaborSummaryModal({
  isOpen,
  onClose,
  defaultDate
}: DailyLaborSummaryModalProps) {
  const { projects, activities, labourLogs, currentUserProfile } = useAppContext();
  
  const [selectedDate, setSelectedDate] = useState<string>(
    defaultDate || new Date().toISOString().split('T')[0]
  );
  
  const printRef = useRef<HTMLDivElement>(null);

  // Filter and Aggregate Data
  const aggregatedData = useMemo(() => {
    const logsForDate = labourLogs.filter(log => log.date === selectedDate);
    
    // Group by employee name
    const grouped = logsForDate.reduce((acc, log) => {
      const name = log.workerName || log.trade || 'Unknown Employee';
      if (!acc[name]) {
        acc[name] = {
          name,
          trade: log.trade || '',
          totalHours: 0,
          entries: []
        };
      }
      
      const projectName = projects.find(p => p.id === log.projectId)?.name || log.projectId;
      const activityName = activities.find(a => a.id === log?.activityId)?.name || log?.activityId || 'General Labor';
      
      acc[name].totalHours += (log.hoursWorked || log.hours || 0);
      acc[name].entries.push({
        ...log,
        projectName,
        activityName
      });
      
      return acc;
    }, {} as Record<string, { name: string, trade: string, totalHours: number, entries: (LabourLog & { projectName: string, activityName: string })[] }>);
    
    // Convert to sorted array
    const resultArr: { name: string, trade: string, totalHours: number, entries: (LabourLog & { projectName: string, activityName: string })[] }[] = Object.values(grouped);
    return resultArr.sort((a, b) => a.name.localeCompare(b.name));
  }, [labourLogs, selectedDate, projects, activities]);

  const grandTotalHours = aggregatedData.reduce((sum, emp) => sum + emp.totalHours, 0);

  const handlePrint = () => {
    handleDownloadPdf();
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF('p', 'pt', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 41, 59);
    doc.text('Daily Labor Hours Summary', 40, 40);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Date: ${new Date(selectedDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 40, 60);
    doc.text(`Generated By: ${currentUserProfile?.name || 'Administrator'}`, 40, 75);
    doc.text(`Generated On: ${new Date().toLocaleString()}`, 40, 90);
    
    // Overall Stats
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Summary Statistics', 40, 120);
    
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text(`Total Employees: ${aggregatedData.length}`, 40, 135);
    doc.text(`Total Labor Hours: ${grandTotalHours.toFixed(2)} hrs`, 180, 135);
    
    let yPos = 160;
    
    // Employee Breakdown
    aggregatedData.forEach((emp) => {
      // Add page break if near bottom
      if (yPos > doc.internal.pageSize.getHeight() - 100) {
        doc.addPage();
        yPos = 40;
      }
      
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42);
      doc.text(`${emp.name} (${emp.trade}) - Total: ${emp.totalHours.toFixed(2)} hrs`, 40, yPos);
      yPos += 10;
      
      const tableData = emp.entries.map(entry => [
        entry.projectName,
        entry.activityName,
        entry.startTime || '-',
        entry.endTime || '-',
        entry.lunchBreak ? `${entry.lunchBreak} hr` : '-',
        `${(entry.hoursWorked || entry.hours || 0).toFixed(2)} hrs`
      ]);
      
      autoTable(doc, {
        startY: yPos,
        head: [['Project', 'Task / Activity', 'Start', 'End', 'Lunch Break', 'Hours']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontSize: 9 },
        styles: { fontSize: 8, textColor: [51, 65, 85] },
        columnStyles: {
          0: { cellWidth: 120 },
          1: { cellWidth: 150 },
          2: { cellWidth: 50 },
          3: { cellWidth: 50 },
          4: { cellWidth: 60 },
          5: { cellWidth: 60, halign: 'right' }
        },
        margin: { left: 40, right: 40 }
      });
      
      yPos = (doc as any).lastAutoTable.finalY + 30;
    });
    
    doc.save(`Daily_Labor_Summary_${selectedDate}.pdf`);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto print:bg-white print:p-0 print:block">
      <Card className="w-full max-w-4xl shadow-2xl border-slate-200 dark:border-slate-800 flex flex-col max-h-full print:shadow-none print:border-none print:w-full print:max-w-full print:h-auto">
        {/* Header - Hidden when printing */}
        <div className="flex items-center justify-between p-4 sm:p-6 border-b border-slate-100 dark:border-slate-800 shrink-0 print:hidden">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-indigo-50 dark:bg-indigo-900/30 rounded-xl text-indigo-600 dark:text-indigo-400">
              <FileText className="h-6 w-6" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900 dark:text-white">Daily Labor Summary</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Review and print aggregated hours by date</p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-lg text-xs font-bold transition-colors"
            >
              <Printer className="h-4 w-4" /> Print
            </button>
            <button
              onClick={handleDownloadPdf}
              className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition-colors"
            >
              <Download className="h-4 w-4" /> Download PDF
            </button>
            <button
              onClick={onClose}
              className="p-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-600 dark:text-slate-400 rounded-lg transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Filters - Hidden when printing */}
        <div className="p-4 sm:p-6 bg-slate-50 dark:bg-slate-900 border-b border-slate-100 dark:border-slate-800 shrink-0 print:hidden">
          <div className="flex items-center gap-4">
            <div>
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">Select Date</label>
              <input 
                type="date"
                className="px-3 py-2 bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg text-sm font-medium text-slate-900 dark:text-slate-100"
                value={selectedDate}
                onChange={(e) => setSelectedDate(e.target.value)}
              />
            </div>
          </div>
        </div>

        {/* Printable Content */}
        <div className="p-4 sm:p-8 overflow-y-auto print:p-0 print:overflow-visible">
          {aggregatedData.length === 0 ? (
            <div className="text-center py-12 print:hidden">
              <Calendar className="h-12 w-12 text-slate-300 dark:text-slate-700 mx-auto mb-3" />
              <h3 className="text-lg font-semibold text-slate-600 dark:text-slate-300">No Hours Logged</h3>
              <p className="text-sm text-slate-500">There are no labor hours recorded for {new Date(selectedDate).toLocaleDateString()}.</p>
            </div>
          ) : (
            <div className="space-y-8" ref={printRef}>
              
              {/* Document Header (Shows mostly when printing) */}
              <div className="border-b-2 border-slate-900 pb-4 mb-6">
                <h1 className="text-2xl font-black text-slate-900 dark:text-white uppercase tracking-tight">Daily Labor Report</h1>
                <div className="flex items-center justify-between mt-2 text-sm text-slate-600 dark:text-slate-400">
                  <p><strong>Date:</strong> {new Date(selectedDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                  <p><strong>Total Employees:</strong> {aggregatedData.length}</p>
                  <p><strong>Total Hours:</strong> <span className="font-bold text-slate-900 dark:text-white">{grandTotalHours.toFixed(2)} hrs</span></p>
                </div>
              </div>

              {/* Employee Breakdown */}
              <div className="space-y-6">
                {aggregatedData.map(emp => (
                  <div key={emp.name} className="break-inside-avoid border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden print:border-none print:mb-6">
                    <div className="bg-slate-100 dark:bg-slate-800/50 px-4 py-3 flex items-center justify-between print:bg-transparent print:border-b print:border-slate-300 print:px-0">
                      <div className="flex items-center gap-3">
                        <div className="h-8 w-8 rounded-full bg-slate-200 dark:bg-slate-700 flex items-center justify-center text-slate-600 dark:text-slate-300 font-bold print:hidden">
                          {emp.name.substring(0, 2).toUpperCase()}
                        </div>
                        <div>
                          <h3 className="text-sm font-bold text-slate-900 dark:text-white">{emp.name}</h3>
                          <p className="text-[10px] text-slate-500 uppercase tracking-wider">{emp.trade}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-0.5">Total Hours</p>
                        <p className="text-sm font-black text-indigo-600 dark:text-indigo-400">{emp.totalHours.toFixed(2)} hrs</p>
                      </div>
                    </div>
                    
                    <div className="p-0">
                      <table className="w-full text-left text-xs">
                        <thead className="bg-slate-50 dark:bg-slate-900/40 text-slate-500 border-b border-slate-200 dark:border-slate-800 print:bg-transparent">
                          <tr>
                            <th className="px-4 py-2 font-semibold">Project</th>
                            <th className="px-4 py-2 font-semibold">Task / Activity</th>
                            <th className="px-4 py-2 font-semibold text-center">Start</th>
                            <th className="px-4 py-2 font-semibold text-center">End</th>
                            <th className="px-4 py-2 font-semibold text-center">Lunch</th>
                            <th className="px-4 py-2 font-semibold text-right">Hours</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800 print:divide-slate-200">
                          {emp.entries.map((entry, idx) => (
                            <tr key={idx} className="bg-white dark:bg-slate-950 print:bg-transparent">
                              <td className="px-4 py-2.5 text-slate-700 dark:text-slate-300">
                                <div className="flex items-center gap-1.5">
                                  <Building className="h-3 w-3 text-slate-400 print:hidden" />
                                  <span className="font-medium truncate max-w-[150px]">{entry.projectName}</span>
                                </div>
                              </td>
                              <td className="px-4 py-2.5 text-slate-600 dark:text-slate-400">
                                <span className="truncate max-w-[200px] block">{entry.activityName}</span>
                                {entry.notes && <span className="block text-[10px] text-slate-400 italic mt-0.5 truncate max-w-[200px]">{entry.notes.replace(/^.*?: /, '')}</span>}
                              </td>
                              <td className="px-4 py-2.5 text-slate-600 dark:text-slate-400 text-center font-mono">
                                {entry.startTime || '-'}
                              </td>
                              <td className="px-4 py-2.5 text-slate-600 dark:text-slate-400 text-center font-mono">
                                {entry.endTime || '-'}
                              </td>
                              <td className="px-4 py-2.5 text-slate-500 text-center">
                                {entry.lunchBreak ? `${entry.lunchBreak} hr` : '-'}
                              </td>
                              <td className="px-4 py-2.5 font-bold text-slate-900 dark:text-white text-right">
                                {(entry.hoursWorked || entry.hours || 0).toFixed(2)}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                ))}
              </div>
              
              {/* Footer */}
              <div className="mt-12 pt-4 border-t border-slate-200 dark:border-slate-800 text-center text-[10px] text-slate-400">
                <p>Generated by ConstructOS • {new Date().toLocaleString()}</p>
              </div>

            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
